// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"errors"

	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/metric/noop"
	"go.opentelemetry.io/otel/trace"

	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/collector/config/configtelemetry"
)

func Meter(settings component.TelemetrySettings) metric.Meter {
	return settings.MeterProvider.Meter("otelcol/reduce")
}

func Tracer(settings component.TelemetrySettings) trace.Tracer {
	return settings.TracerProvider.Tracer("otelcol/reduce")
}

// TelemetryBuilder provides an interface for components to report telemetry
// as defined in metadata and user config.
type TelemetryBuilder struct {
	meter                   metric.Meter
	ReduceProcessorCombined metric.Int64Histogram
	ReduceProcessorOutput   metric.Int64Counter
	ReduceProcessorReceived metric.Int64Counter
	level                   configtelemetry.Level
}

// telemetryBuilderOption applies changes to default builder.
type telemetryBuilderOption func(*TelemetryBuilder)

// WithLevel sets the current telemetry level for the component.
func WithLevel(lvl configtelemetry.Level) telemetryBuilderOption {
	return func(builder *TelemetryBuilder) {
		builder.level = lvl
	}
}

// NewTelemetryBuilder provides a struct with methods to update all internal telemetry
// for a component
func NewTelemetryBuilder(settings component.TelemetrySettings, options ...telemetryBuilderOption) (*TelemetryBuilder, error) {
	builder := TelemetryBuilder{level: configtelemetry.LevelBasic}
	for _, op := range options {
		op(&builder)
	}
	var err, errs error
	if builder.level >= configtelemetry.LevelBasic {
		builder.meter = Meter(settings)
	} else {
		builder.meter = noop.Meter{}
	}
	builder.ReduceProcessorCombined, err = builder.meter.Int64Histogram(
		"otelcol_reduce_processor_combined",
		metric.WithDescription("Number of log events that were combined"),
		metric.WithUnit("{records}"),
	)
	errs = errors.Join(errs, err)
	builder.ReduceProcessorOutput, err = builder.meter.Int64Counter(
		"otelcol_reduce_processor_output",
		metric.WithDescription("Number of aggreated log events output"),
		metric.WithUnit("{records}"),
	)
	errs = errors.Join(errs, err)
	builder.ReduceProcessorReceived, err = builder.meter.Int64Counter(
		"otelcol_reduce_processor_received",
		metric.WithDescription("Number of log events received"),
		metric.WithUnit("{records}"),
	)
	errs = errors.Join(errs, err)
	return &builder, errs
}
