// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"errors"

	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/metric/embedded"
	"go.opentelemetry.io/otel/trace"

	"go.opentelemetry.io/collector/component"
)

func Meter(settings component.TelemetrySettings) metric.Meter {
	return settings.MeterProvider.Meter("otelcol/bytecounter")
}

func Tracer(settings component.TelemetrySettings) trace.Tracer {
	return settings.TracerProvider.Tracer("otelcol/bytecounter")
}

// TelemetryBuilder provides an interface for components to report telemetry
// as defined in metadata and user config.
type TelemetryBuilder struct {
	meter             metric.Meter
	mu                sync.Mutex
	registrations     []metric.Registration
	LogsBytesCount    metric.Int64Counter
	MetricsBytesCount metric.Int64Counter
	TracesBytesCount  metric.Int64Counter
}

// TelemetryBuilderOption applies changes to default builder.
type TelemetryBuilderOption interface {
	apply(*TelemetryBuilder)
}

type telemetryBuilderOptionFunc func(mb *TelemetryBuilder)

func (tbof telemetryBuilderOptionFunc) apply(mb *TelemetryBuilder) {
	tbof(mb)
}

// Shutdown unregister all registered callbacks for async instruments.
func (builder *TelemetryBuilder) Shutdown() {
	builder.mu.Lock()
	defer builder.mu.Unlock()
	for _, reg := range builder.registrations {
		reg.Unregister()
	}
}

// NewTelemetryBuilder provides a struct with methods to update all internal telemetry
// for a component
func NewTelemetryBuilder(settings component.TelemetrySettings, options ...TelemetryBuilderOption) (*TelemetryBuilder, error) {
	builder := TelemetryBuilder{}
	for _, op := range options {
		op.apply(&builder)
	}
	builder.meter = Meter(settings)
	var err, errs error
	builder.LogsBytesCount, err = builder.meter.Int64Counter(
		"otelcol_logs_bytes_count",
		metric.WithDescription("Count of logs bytes processed by the processor"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.MetricsBytesCount, err = builder.meter.Int64Counter(
		"otelcol_metrics_bytes_count",
		metric.WithDescription("Count of metrics bytes processed by the processor"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.TracesBytesCount, err = builder.meter.Int64Counter(
		"otelcol_traces_bytes_count",
		metric.WithDescription("Count of traces bytes processed by the processor"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	return &builder, errs
}
