// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("dynamic_sampler")
	ScopeName = "otelcol/dynamicsampling"
)

const (
	LogsStability = component.StabilityLevelDevelopment
)
