// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("honeycomb")
	ScopeName = "github.com/honeycombio/opentelemetry-collector-configs/honeycombextension"
)

const (
	ExtensionStability = component.StabilityLevelDevelopment
)
