// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"errors"
	"sync"

	"go.opentelemetry.io/otel/metric"
	_ "go.opentelemetry.io/otel/metric/embedded"
	"go.opentelemetry.io/otel/trace"

	"go.opentelemetry.io/collector/component"
)

func Meter(settings component.TelemetrySettings) metric.Meter {
	return settings.MeterProvider.Meter("github.com/honeycombio/opentelemetry-collector-configs/honeycombextension")
}

func Tracer(settings component.TelemetrySettings) trace.Tracer {
	return settings.TracerProvider.Tracer("github.com/honeycombio/opentelemetry-collector-configs/honeycombextension")
}

// TelemetryBuilder provides an interface for components to report telemetry
// as defined in metadata and user config.
type TelemetryBuilder struct {
	meter                                  metric.Meter
	mu                                     sync.Mutex
	registrations                          []metric.Registration
	HoneycombExtensionBytesReceivedLogs    metric.Int64Counter
	HoneycombExtensionBytesReceivedMetrics metric.Int64Counter
	HoneycombExtensionBytesReceivedTraces  metric.Int64Counter
	HoneycombExtensionUsageReportFailure   metric.Int64Counter
	HoneycombExtensionUsageReportSuccess   metric.Int64Counter
}

// TelemetryBuilderOption applies changes to default builder.
type TelemetryBuilderOption interface {
	apply(*TelemetryBuilder)
}

type telemetryBuilderOptionFunc func(mb *TelemetryBuilder)

func (tbof telemetryBuilderOptionFunc) apply(mb *TelemetryBuilder) {
	tbof(mb)
}

// Shutdown unregister all registered callbacks for async instruments.
func (builder *TelemetryBuilder) Shutdown() {
	builder.mu.Lock()
	defer builder.mu.Unlock()
	for _, reg := range builder.registrations {
		reg.Unregister()
	}
}

// NewTelemetryBuilder provides a struct with methods to update all internal telemetry
// for a component
func NewTelemetryBuilder(settings component.TelemetrySettings, options ...TelemetryBuilderOption) (*TelemetryBuilder, error) {
	builder := TelemetryBuilder{}
	for _, op := range options {
		op.apply(&builder)
	}
	builder.meter = Meter(settings)
	var err, errs error
	builder.HoneycombExtensionBytesReceivedLogs, err = builder.meter.Int64Counter(
		"otelcol_honeycomb_extension_bytes_received_logs",
		metric.WithDescription("Total bytes received from logs singal"),
		metric.WithUnit("{records}"),
	)
	errs = errors.Join(errs, err)
	builder.HoneycombExtensionBytesReceivedMetrics, err = builder.meter.Int64Counter(
		"otelcol_honeycomb_extension_bytes_received_metrics",
		metric.WithDescription("Total bytes received from metrcis singal"),
		metric.WithUnit("{records}"),
	)
	errs = errors.Join(errs, err)
	builder.HoneycombExtensionBytesReceivedTraces, err = builder.meter.Int64Counter(
		"otelcol_honeycomb_extension_bytes_received_traces",
		metric.WithDescription("Total bytes received from trace singal"),
		metric.WithUnit("{records}"),
	)
	errs = errors.Join(errs, err)
	builder.HoneycombExtensionUsageReportFailure, err = builder.meter.Int64Counter(
		"otelcol_honeycomb_extension_usage_report_failure",
		metric.WithDescription("Total usage report failure"),
		metric.WithUnit("{records}"),
	)
	errs = errors.Join(errs, err)
	builder.HoneycombExtensionUsageReportSuccess, err = builder.meter.Int64Counter(
		"otelcol_honeycomb_extension_usage_report_success",
		metric.WithDescription("Total usage report success"),
		metric.WithUnit("{records}"),
	)
	errs = errors.Join(errs, err)
	return &builder, errs
}
